name: Continuous Integration with Github Actions

on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    
    - name: Build Application Jar
      run: mvn clean package -DskipTests  
      working-directory: .

    - name: Docker Compose Build
      run:  docker compose up -d --build
      working-directory: .
      
    - name: Push to Docker Hub Container registry
      run: |
        docker tag rest-api-with-spring-boot-rest-api-with-spring-boot ${{ secrets.DOCKER_USERNAME }}/rest-api-with-spring-boot-rest-api-with-spring-boot:${{github.run_id}}  
     
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-api-with-spring-boot-rest-api-with-spring-boot:${{github.run_id}}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-api-with-spring-boot-rest-api-with-spring-boot:latest
